<div class="clearfix"></div>
<div id="navbar-right" class="navbar navbar-inverse navbar-fixed-top-right">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			<span class="sr-only">Toggle Navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a href="navbar-brand" href="#" title="Home" rel="home">
			<h3 class="site-title">Membres</h3>
		</a>
	</div>
	<div class="clearfix"></div>
	<div class="js_footer collapse navbar-collapse">
		<ul class="nav nav-stacked" id="menu-bar">
			<?php require('module/user/apps/list_users.php') ?>
		</ul>
	</div>
</div>