<div id="navbar-left" class="navbar navbar-inverse navbar-fixed-top-left">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			<span class="sr-only">Toggle Navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a href="navbar-brand" href="#" title="Home" rel="home">
			<h3 class="site-title">TCHAT  COWORKING</h3>
		</a>
	</div>
	<div class="clearfix"></div>
	<div class="collapse navbar-collapse">
		<div class="navbar-form">
			<form method="POST">
				<div class="form-group">
					<label for="login">Login</label>
					<input type="text" class="form-control" id="login" name="login" placeholder="Login">
				</div>
				<div class="form-group">
					<label for="password">Password</label>
					<input type="password" class="form-control" id="password" name="password" placeholder="Password">
				</div>
				<button type="submit" class="btn btn-success navbar-btn" name="action" value="login">Connecter</button>
			</form>
		</div>
	</div>

	<div class="clearfix"></div>
	<div class="collapse navbar-collapse">
<!-- 			<ul class="nav nav-stacked" id="menu-bar">
		    <li><a href="#">Home</a></li>
		    <li><a href="#">Page 1</a></li>
		    <li class="panel dropdown"> 
		            <a data-toggle="collapse" data-parent="#menu-bar" href="#collapseOne">
		              Collapsible Item 1
		            </a>
				<ul id="collapseOne" class="panel-collapse collapse"> 
				    <li><a href="#">Item 1</a></li>
				    <li><a href="#">Item 2</a></li>
				</ul>
			</li>
		    <li class="panel dropdown">
		        <a data-toggle="collapse" data-parent="#menu-bar" href="#collapseTwo">
		              Collapsible Item 2
		        </a>
				<ul id="collapseTwo" class="panel-collapse collapse">
				    <li><a href="#">Item 2-1</a></li>
				    <li><a href="#">Item 2-2</a></li>
				</ul>
			</li>
		    <li><a href="#">Page 3</a></li>
		    <li><a href="#">Page 4</a></li>
		</ul> -->
	</div>
</div>