<div class="col-xs-12">
	<div class="jumbotron">
	<div >
	  <div class="modal-header">
	    <h2 class="modal-title" id="modal-label-register">Inscription</h2>
	  </div>
	  <div class="modal-body">
		<form method="POST" enctype="multipart/form-data">
			<div class="form-group">
				<label for="login">Login</label>
				<input type="text" class="form-control" id="login" name="login" placeholder="Login">
			</div>
		 	<div class="form-group">
		    	<label for="avatar">Avatar</label>
		    	<input type="file" id="avatar" name="avatar">
		    	<p class="help-block">Intégrer votre avatar.</p>
		 	</div>
			<div class="form-group">
				<label for="password1">Mot de passe</label>
				<input type="password" class="form-control" id="password1" name="password1" placeholder="Mot de passe">
			</div>
			<div class="form-group">
				<label for="password2">Retaper votre mot de passe</label>
				<input type="password" class="form-control" id="password2" name="password2" placeholder="Retaper votre mot de passe">
			</div>
			<button type="submit" class="btn btn-success" name="action" value="register">Créer votre compte</button>
		</form>

	  </div>
	</div>
	</div>
   
</div>

