<div class="col-xs-12 wrapper-messages">
	<div class="modal-header">
	    <!-- <h3 class="modal-title" id="modal-label-register">Messages</h3> -->
	    <form method="POST" class="js_more">
			<button type="submit" class="btn_nue" name="action" value="more_message" >Plus de messages...</button>
		</form>
	</div>
	<div class="">
		<form method="POST" class="js_form">
			<div class="js_list" id="js_list">
				<?php require('module/message/apps/listMessage.php'); ?>
			</div>
			<div class="wrapper-create-message">
				<?php require('module/message/apps/createMessage.php'); ?>
			</div>
		</form>
	</div>
</div>