<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<title>Tchat Coworking</title>
		<meta name="viewport" content="width=device-width, user-scalable=no">
		<link rel="stylesheet" type="text/css" href="public/STYLES/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="public/STYLES/bootstrap-theme.min.css">
		<link rel="stylesheet" type="text/css" href="public/STYLES/style.css">
		<script type="text/javascript" src="public/SCRIPTS/jquery.min.js"></script>
		<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
		<script type="text/javascript" src="public/SCRIPTS/bootstrap.min.js"></script>
		<script type="text/javascript" src="public/SCRIPTS/script.js"></script>
	</head>
<body>
	<div class="row">
		<?php require('apps/header.php'); ?>
	</div>
	<div class="row">
		<?php require('apps/content.php'); ?>
		<div class="scrollup"></div>
	</div>
	<div class="row">
		<?php require('apps/footer.php'); ?>
	</div>
</body>
</html>
