<div class="create-message">
	<div class="center-create-message">
		<div class="row">
			<div class="col-xs-1">
				<button type="submit" class="form_create_message glyphicon glyphicon-camera" name="action" value="create_message" ></button>
			</div>
			<div class="col-xs-10">
				<!-- <input type="hidden" name="IdUser" value="<?=htmlentities($_SESSION['id'])?>"> -->
				<input type="text" class="js_in form_create_message form-control" id="create_message" name="content" value="" autofocus autocomplete="off">
			</div>
			<div class="col-xs-1 submit">
				<button type="submit" class="form_create_message glyphicon glyphicon-expand" name="action" value="create_message" ></button>
			</div>
		</div>
	</div>
</div>



  


